### ISSUE TITLE
test_mecab.py::test_match failed

### ISSUE THREAD

**Issue by hideaki-t** [hideaki-t/sqlite-fts-python#15]
not sure what happened, but it seems it is failing. Python 3.7+MeCab worked before

```
test_mecab.py::test_createtable PASSED
test_mecab.py::test_insert PASSED
test_mecab.py::test_match FAILED
test_mecab.py::test_tokenizer_output From cffi callback <function make_tokenizer_module.<locals>.xclose at 0x7f0163659730>:
Traceback (most recent call last):
  File "/home/hideaki/sqlite-fts-python/tests/jajp_common.py", line 70, in test_tokenizer_output
    assert e == a
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hideaki/sqlite-fts-python/.tox/py37-linux/lib/python3.7/site-packages/sqlitefts/fts3.py", line 132, in xclose
    tk = ffi.from_handle(pCursor.pTokenizer.t)
  File "/home/hideaki/sqlite-fts-python/.tox/py37-linux/lib/python3.7/site-packages/cffi/api.py", line 540, in from_handle
    return self._backend.from_handle(x)
SystemError: <built-in function from_handle> returned a result with an error set
ERROR: InvocationError for command /home/hideaki/sqlite-fts-python/.tox/py37-linux/bin/py.test -svrx (exited with code -11)
```

**Comment by hideaki-t** [comment]
cannot reproduce using 3.8 and mecab (not mecab-python3)
